const colors = {
  light: {
    accent: '#f4f4f5',
    accent_foreground: '#18181b',
    background: '#ffffff',
    border: '#e4e4e7',
    card: '#ffffff',
    card_foreground: '#09090b',
    destructive: '#dc2626',
    destructive_foreground: '#fef2f2',
    foreground: '#18181b',
    input: '#e4e4e7',
    muted: '#f4f4f5',
    muted_foreground: '#71717a',
    popover: '#ffffff',
    popover_foreground: '#09090b',
    primary: '#0b3994',
    primary_foreground: '#fafafa',
    ring: '#18181b',
    ring_offset: '#ffffff',
    secondary: '#f4f4f5',
    secondary_foreground: '#18181b',
    chart_1: '#2a9d90',
    chart_2: '#e76e50',
    chart_3: '#274754',
    chart_4: '#e8c468',
    chart_5: '#f4a462',
    sidebar_background: '#fafafa',
    sidebar_foreground: '#3f3f46',
    sidebar_primary: '#18181b',
    sidebar_primary_foreground: '#fafafa',
    sidebar_accent: '#f4f4f5',
    sidebar_accent_foreground: '#18181b',
    sidebar_border: '#e5e7eb',
    sidebar_ring: '#a1a1aa',
    warn: '#f4a462',
    warn_foreground: '#FEE9C1',
    success: '#2a9d90',
    success_foreground: '#EFF7EF',
  },
  dark: {
    accent: '#27272a',
    accent_foreground: '#fafafa',
    background: '#09090b',
    border: '#27272a',
    card: '#09090b',
    card_foreground: '#fafafa',
    destructive: '#7f1d1d',
    destructive_foreground: '#fef2f2',
    foreground: '#fafafa',
    input: '#27272a',
    muted: '#27272a',
    muted_foreground: '#a1a1aa',
    popover: '#09090b',
    popover_foreground: '#fafafa',
    primary: '#75a0f5',
    primary_foreground: '#18181b',
    ring: '#d4d4d8',
    ring_offset: '#ffffff',
    secondary: '#27272a',
    secondary_foreground: '#fafafa',
    chart_1: '#2662d9',
    chart_2: '#e23670',
    chart_3: '#e88c30',
    chart_4: '#af57db',
    chart_5: '#2eb88a',
    sidebar_background: '#18181b',
    sidebar_foreground: '#f4f4f5',
    sidebar_primary: '#1d4ed8',
    sidebar_primary_foreground: '#ffffff',
    sidebar_accent: '#27272a',
    sidebar_accent_foreground: '#f4f4f5',
    sidebar_border: '#27272a',
    sidebar_ring: '#d4d4d8',
    warn: '#f4a462',
    warn_foreground: '#FEE9C1',
    success: '#2a9d90',
    success_foreground: '#EFF7EF',
  },
} as const;

export default colors;

export type ColorTheme = typeof colors;
export type ColorMode = keyof ColorTheme;
export type TypeColorKeys = keyof ColorTheme['light'];
export type ColorValue = ColorTheme['light'][TypeColorKeys];